import Head from "next/head";
import { Fragment, useState } from "react";
import { makeStyles } from "@mui/styles";
import { Box, Tabs, Tab, Grid, Button } from "@mui/material";
import KeyIcon from "@mui/icons-material/KeyOutlined";

import TabPanel from "../components/TabPanel/TabPanel";
import styles from "../styles/About.module.css";
import Buy from "../components/Action/Buy";
import Vault from "../components/Action/Vault";
import Recommend from "../components/Action/Recommend";
import Round from "../components/Action/Round";

const useStyles = makeStyles((theme) => ({
  tabBox: {
    display: "flex",
    "& .Mui-selected": {
      backgroundColor: "#343a40 !important",
    },
    "& .MuiButtonBase-root .MuiTab-root": {
      backgroundColor: "transparent",
    },
  },
}));

const firstProps = (index) => {
  return {
    id: `simple-tab-${index}`,
    "aria-controls": `simple-tabpanel-${index}`,
  };
};

const secondProps = (index) => {
  return {
    id: `simple-tab-${index}`,
    "aria-controls": `simple-tabpanel-${index}`,
  };
};

const About = () => {
  const classes = useStyles();
  const [actionValue, setActionValue] = useState(0);
  const [recordValue, setRecordValue] = useState(0);

  const [totalPot, setTotalPot] = useState(0);

  const handleActionChange = (event, newValue) => {
    setActionValue(newValue);
  };

  const handleRecordChange = (event, newValue) => {
    setRecordValue(newValue);
  };

  return (
    <Fragment>
      <div className={styles.background} />
      <div className={styles.container}>
        <Head>
          <title>Create Next App | About</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Total in pot : {totalPot} BNB</h1>
          <div
            style={{
              color: "white",
              fontSize: "4.5rem",
              textShadow: "0 0 5px #2b002b, 0 0 20px #efad00, 0 0 10px #efad00",
            }}
          >
            0.0019 BNB
          </div>
          <div style={{ color: "white", fontSize: "2rem" }}>
            被
            <a
              style={{
                color: "white",
                textDecoration: "underline",
                cursor: "pointer",
              }}
            >
              0x00000000...
            </a>
            卷走！
          </div>
          <span className={styles.text}>购买至少一个钥匙来开启新一轮游戏</span>
          <Button
            className={`${styles.btnGold} ${styles.btnSize}`}
            href="/about"
          >
            <div style={{ display: "flex", alignItems: "center" }}>
              1x
              <KeyIcon style={{ transform: "rotate(135deg)" }} />
            </div>
            <div style={{ display: "flex", alignItems: "center" }}>
              立即梭哈
            </div>
          </Button>
          <Grid container className={styles.tabBox}>
            <Grid item className={styles.tab} lg={5} md={6} sm={11} xs={12}>
              <Box
                sx={{
                  borderBottom: 1,
                  borderColor: "divider",
                  "& .MuiTabs-flexContainer": {
                    borderBottom: "1px solid #dee2e6",
                  },
                  "& .Mui-selected": {
                    color: "white !important",
                    backgroundColor: "#343a40",
                    marginBottom: "-1px",
                    borderTopLeftRadius: "0.25rem",
                    borderTopRightRadius: "0.25rem",
                  },
                }}
              >
                <Tabs
                  value={actionValue}
                  onChange={handleActionChange}
                  aria-label="basic tabs example"
                  indicatorColor="transparent"
                >
                  <Tab
                    label="购买"
                    sx={{
                      color: "white",
                      "&:hover": {
                        backgroundColor: "#2d3238",
                        textShadow:
                          "0 0 2px #2b002b, 0 0 25px #c0c, 0 0 5px #f0f",
                      },
                    }}
                    {...firstProps(0)}
                  />
                  <Tab
                    label="金库"
                    sx={{
                      color: "white",
                      "&:hover": {
                        backgroundColor: "#2d3238",
                        textShadow:
                          "0 0 2px #2b002b, 0 0 25px #c0c, 0 0 5px #f0f",
                      },
                    }}
                    {...firstProps(1)}
                  />
                  <Tab
                    label="推荐奖励"
                    sx={{
                      color: "white",
                      "&:hover": {
                        backgroundColor: "#2d3238",
                        textShadow:
                          "0 0 2px #2b002b, 0 0 25px #c0c, 0 0 5px #f0f",
                      },
                    }}
                    {...firstProps(2)}
                  />
                </Tabs>
              </Box>
              <TabPanel value={actionValue} index={0}>
                <Buy />
              </TabPanel>
              <TabPanel value={actionValue} index={1}>
                <Vault />
              </TabPanel>
              <TabPanel value={actionValue} index={2}>
                <Recommend />
              </TabPanel>
            </Grid>
            <Grid item className={styles.tab} lg={5} md={6} sm={11} xs={12}>
              <Box
                sx={{
                  borderBottom: 1,
                  borderColor: "divider",
                  "& .MuiTabs-flexContainer": {
                    borderBottom: "1px solid #dee2e6",
                  },
                  "& .Mui-selected": {
                    color: "white !important",
                    marginBottom: "-10px",
                    backgroundColor: "#343a40",
                    borderTopLeftRadius: "0.25rem",
                    borderTopRightRadius: "0.25rem",
                  },
                }}
              >
                <Tabs
                  value={recordValue}
                  onChange={handleRecordChange}
                  aria-label="basic tabs example"
                  indicatorColor="transparent"
                >
                  <Tab
                    label="回合"
                    sx={{ color: "white" }}
                    {...secondProps(0)}
                  />
                  <Tab
                    label="团队"
                    sx={{ color: "white" }}
                    {...secondProps(1)}
                  />
                  <Tab
                    label="统计"
                    sx={{ color: "white" }}
                    {...secondProps(2)}
                  />
                </Tabs>
              </Box>
              <TabPanel value={recordValue} index={0}>
                <Round />
              </TabPanel>
              <TabPanel value={recordValue} index={1}>
                暂无
              </TabPanel>
              <TabPanel value={recordValue} index={2}>
                暂无
              </TabPanel>
            </Grid>
          </Grid>
        </main>
      </div>
    </Fragment>
  );
};

export default About;
