import Head from "next/head";
import { Fragment } from "react";
import { useSelector } from "react-redux";
import { Box, Button } from "@mui/material";
import styles from "../styles/Admin.module.css";

export default function admin() {
  const userAddress = useSelector((state) => state.user_address);
  return (
    <Fragment>
      <div className={styles.background} />
      <div className={styles.container}>
        <Head>
          <title>FOMO-3D | Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Fomo3D Admin Console</h1>
          <Box sx={{ p: 3 }}>
            <h3 className={styles.subtitle}>
              Login in account：
              {userAddress.slice(0, 7) +
                "...." +
                userAddress.substring(userAddress?.length - 5)}
            </h3>
            <div
              style={{
                backgroundColor: "#343a40",
                color: "white",
                borderRadius: "1rem",
                padding:"1rem"
              }}
            >
              <div className={styles.showInfo}>
                <Button className={styles.btn}>Rug all BNB in pot</Button>
                <Button className={styles.btn}>
                  Let your be the last winner
                </Button>
                <Button className={styles.btn}>Shut down this game</Button>
              </div>
            </div>
          </Box>
        </main>
      </div>
    </Fragment>
  );
}
