import Head from "next/head";
import { Fragment } from "react";
import { Box, Button } from "@mui/material";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Fragment>
      <div className={styles.background} />
      <div className={styles.container}>
        <Head>
          <title>FOMO-3D | Index</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Box
            sx={{
              display: "flex",
              width: "100%",
              height: "100vh",
              background: "transparent",
              alignItems: "center",
              justifyContent: "center",
              color: "white",
            }}
          >
            <Button
              className={`${styles.btnGold} ${styles.btnSize}`}
              href="/about"
            >
              Now Exit Scamming
            </Button>
          </Box>
        </main>
      </div>
    </Fragment>
  );
}
